function Cigbill(){var lb='',X=' top: -1000px;',ub='" for "gwt:onLoadErrorFn"',sb='" for "gwt:onPropertyErrorFn"',eb='");',vb='#',Hb='&',kc='.cache.js',xb='/',Db='//',Zb='0FB7D9225379DCCED51AAEC0F3A92FC5',$b='16F64080E2147C718B9EE59119FE7FE7',_b='2AED8A559271A8BF98E01BC63F243C04',ac='2DAFA2D1F6B356BA8621B1DC62CC84AE',bc='62586467B44A44767B497DA5727F0F31',cc='9A653AF16B645D8F6FE2D6E22543DADB',jc=':',mb='::',oc=':moduleBase',Y='<html><head><\/head><body><\/body><\/html>',pb='=',wb='?',dc='A8BF4C78D038F25B01B7E4E956BADB5D',ec='A9C0682AF3D7BEA6C55B196A05A48148',fc='BD8C0223C97970803F2707DBA2B9DA93',rb='Bad handler "',cb='Chrome',Q='Cigbill',Xb='Cigbill.devmode.js',Bb='Cigbill.nocache.js',kb='Cigbill::',gc='D6BCE66411F83B6C99EBEB63460E3AD5',bb='DOMContentLoaded',S='DUMMY',hc='E8EE70AB5493D958D769226EF8DAFE0B',ic='FEE1B29EEE515F14B5982B3E5B62E81F',Kb='Unexpected exception in locale detection, using default: ',Jb='_',nc='__gwtDevModeHook:Cigbill',Ib='__gwt_Locale',Cb='base',Ab='baseUrl',N='begin',T='body',M='bootstrap',zb='clear.cache.gif',ob='content',Yb='default',Fb='en',mc='end',db='eval("',Tb='gecko',Ub='gecko1_8',O='gwt.codesvr.Cigbill=',P='gwt.codesvr=',tb='gwt:onLoadErrorFn',qb='gwt:onPropertyErrorFn',nb='gwt:property',hb='head',Sb='ie6',Rb='ie8',Qb='ie9',U='iframe',yb='img',$='javascript',V='javascript:""',lc='loadExternalRefs',Eb='locale',Gb='locale=',ib='meta',gb='moduleRequested',fb='moduleStartup',Pb='msie',jb='name',Mb='opera',W='position:absolute; width:0; height:0; border:none; left: -1000px;',Ob='safari',Z='script',Wb='selectingPermutation',R='startup',ab='undefined',Vb='unknown',Lb='user.agent',_='var $wnd = window.parent;',Nb='webkit';var q=window;var r=document;t(M,N);function s(){var a=q.location.search;return a.indexOf(O)!=-1||a.indexOf(P)!=-1}
function t(a,b){if(q.__gwtStatsEvent){q.__gwtStatsEvent({moduleName:Q,sessionId:q.__gwtStatsSessionId,subSystem:R,evtGroup:a,millis:(new Date).getTime(),type:b})}}
Cigbill.__sendStats=t;Cigbill.__moduleName=Q;Cigbill.__errFn=null;Cigbill.__moduleBase=S;Cigbill.__softPermutationId=0;Cigbill.__computePropValue=null;Cigbill.__getPropMap=null;Cigbill.__gwtInstallCode=function(){};Cigbill.__gwtStartLoadingFragment=function(){return null};var u=function(){return false};var v=function(){return null};__propertyErrorFunction=null;var w=q.__gwt_activeModules=q.__gwt_activeModules||{};w[Q]={moduleName:Q};var x;function y(){A();return x}
function z(){A();return x.getElementsByTagName(T)[0]}
function A(){if(x){return}var a=r.createElement(U);a.src=V;a.id=Q;a.style.cssText=W+X;a.tabIndex=-1;r.body.appendChild(a);x=a.contentDocument;if(!x){x=a.contentWindow.document}x.open();x.write(Y);x.close();var b=x.getElementsByTagName(T)[0];var c=x.createElement(Z);c.language=$;var d=_;c.text=d;b.appendChild(c)}
function B(k){function l(a){function b(){if(typeof r.readyState==ab){return typeof r.body!=ab&&r.body!=null}return /loaded|complete/.test(r.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(r.removeEventListener){r.removeEventListener(bb,d,false)}if(e){clearInterval(e)}}}
if(r.addEventListener){r.addEventListener(bb,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=z();var f=y();var g;if(navigator.userAgent.indexOf(cb)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(db));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode(eb));g=f.createElement(Z);g.language=$;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(Z);g.language=$;g.text=c[i];e.appendChild(g);d(e,g)}}}
Cigbill.onScriptDownloaded=function(a){l(function(){m(a)})};t(fb,gb);var n=r.createElement(Z);n.src=k;r.getElementsByTagName(hb)[0].appendChild(n)}
Cigbill.__startLoadingFragment=function(a){return E(a)};Cigbill.__installRunAsyncCode=function(a){var b=z();var c=y().createElement(Z);c.language=$;c.text=a;b.appendChild(c);b.removeChild(c)};function C(){var c={};var d;var e;var f=r.getElementsByTagName(ib);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(jb),k;if(j){j=j.replace(kb,lb);if(j.indexOf(mb)>=0){continue}if(j==nb){k=i.getAttribute(ob);if(k){var l,m=k.indexOf(pb);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=lb}c[j]=l}}else if(j==qb){k=i.getAttribute(ob);if(k){try{d=eval(k)}catch(a){alert(rb+k+sb)}}}else if(j==tb){k=i.getAttribute(ob);if(k){try{e=eval(k)}catch(a){alert(rb+k+ub)}}}}}v=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;Cigbill.__errFn=e}
function D(){function e(a){var b=a.lastIndexOf(vb);if(b==-1){b=a.length}var c=a.indexOf(wb);if(c==-1){c=a.length}var d=a.lastIndexOf(xb,Math.min(c,b));return d>=0?a.substring(0,d+1):lb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=r.createElement(yb);b.src=a+zb;a=e(b.src)}return a}
function g(){var a=v(Ab);if(a!=null){return a}return lb}
function h(){var a=r.getElementsByTagName(Z);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(Bb)!=-1){return e(a[b].src)}}return lb}
function i(){var a=r.getElementsByTagName(Cb);if(a.length>0){return a[a.length-1].href}return lb}
function j(){var a=r.location;return a.href==a.protocol+Db+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==lb){k=h()}if(k==lb){k=i()}if(k==lb&&j()){k=e(r.location.href)}k=f(k);return k}
function E(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return Cigbill.__moduleBase+a}
function F(){var i=[];var j;function k(a,b){var c=i;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var l=[];var m=[];function n(a){var b=m[a](),c=l[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
m[Eb]=function(){var b=null;var c=Fb;try{if(!b){var d=location.search;var e=d.indexOf(Gb);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(Hb,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){b=v(Eb)}if(!b){b=q[Ib]}if(b){c=b}while(b&&!u(Eb,b)){var h=b.lastIndexOf(Jb);if(h<0){b=null;break}b=b.substring(0,h)}}catch(a){alert(Kb+a)}q[Ib]=c;return b||Fb};l[Eb]={'default':0,en:1};m[Lb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Mb)!=-1}())return Mb;if(function(){return b.indexOf(Nb)!=-1}())return Ob;if(function(){return b.indexOf(Pb)!=-1&&r.documentMode>=9}())return Qb;if(function(){return b.indexOf(Pb)!=-1&&r.documentMode>=8}())return Rb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Sb;if(function(){return b.indexOf(Tb)!=-1}())return Ub;return Vb};l[Lb]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};u=function(a,b){return b in l[a]};Cigbill.__getPropMap=function(){var a={};for(var b in l){a[b]=n(b)}return a};Cigbill.__computePropValue=n;q.__gwt_activeModules[Q].bindings=Cigbill.__getPropMap;t(M,Wb);if(s()){return E(Xb)}var o;try{k([Yb,Ob],Zb);k([Fb,Sb],$b);k([Fb,Ub],_b);k([Yb,Mb],ac);k([Yb,Rb],bc);k([Fb,Qb],cc);k([Yb,Qb],dc);k([Fb,Rb],ec);k([Yb,Ub],fc);k([Fb,Mb],gc);k([Fb,Ob],hc);k([Yb,Sb],ic);o=i[n(Eb)][n(Lb)];var p=o.indexOf(jc);if(p!=-1){j=parseInt(o.substring(p+1),10);o=o.substring(0,p)}}catch(a){}Cigbill.__softPermutationId=j;return E(o+kc)}
function G(){if(!q.__gwt_stylesLoaded){q.__gwt_stylesLoaded={}}t(lc,N);t(lc,mc)}
C();Cigbill.__moduleBase=D();w[Q].moduleBase=Cigbill.__moduleBase;var H=F();if(q){q.__gwt_activeModules[Q].canRedirect=true}var I=nc;var J=q.sessionStorage[I];if(J&&!q[I]){q[I]=true;var K=r.createElement(Z);q[I+oc]=D();K.src=J;var L=r.getElementsByTagName(hb)[0];L.insertBefore(K,L.firstElementChild);return false}G();t(M,mc);B(H);return true}
Cigbill.succeeded=Cigbill();